server:
  port: ${PORT:5000}

base-url: /api

spring:
  profiles:
    active: dev

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

mvc:
  hiddenmethod:
    filter:
      enabled: true

jwt:
  sessionTime: 120000000
  secret: secret_key
